# armstrong 
# numbers = (153,370,371,407,1634,8208,9474,54748,92727,93084)
# for number in numbers:
#     a = str(number)

#     numberOfDigit = len(a)
#     ans = 0 
#     for i in a:
#         ans = ans + (int(i)**numberOfDigit)

#     if(ans==number):
#         print(number, "Yes")
#     else:
#         print(number, "No")
# ******************  ******************


# recursion 

# def greet(a):
#     if(a>=1):
#         print("Hello",end=" ")
#         greet(a-1)

# greet(5)

# ******************  ******************


# def table(num,a=1):
#     if(a<=10):
#         print(a*num)
#         table(num,a+1)

# table(5)
# ******************  ******************

# 1-10