// SINGLE INHERITANCE 


// #include<iostream>
// using namespace std;

// class Parent
// {
//     public:
//         void ParentQuality()
//         {
//             cout<< "short tempered" <<endl;
//         }
// };

// class Child : public Parent
// {
//     public:
//         void ChildQuality()
//         {
//             cout << "immature" << endl;
//         }
// };

// int main()
// {
//     // Parent anjali;
//     // anjali.ParentQuality();

//     Child vanshu;
//     vanshu.ChildQuality();
//     vanshu.ParentQuality();
//     return 0;
// }